name: Mobile Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Appium and Pytest
        run: |
          npm install -g appium
          appium driver install uiautomator2
          pip install Appium-Python-Client pytest

      - name: Run Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: |
            appium &
            sleep 10
            APK_PATH=app/build/outputs/apk/debug/app-debug.apk pytest -v -k "not llamada and not bateria"